ruby/rails-talkjs/config/routes.rb
Rails.application.routes.draw do
  get 'chat', to: 'chat#index'
  get 'chat/:id', to: 'chat#conversation', as: 'chat_conversation'
  # other routes
end

ruby/rails-talkjs/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby/rails-talkjs/app/models/user.rb
class User < ApplicationRecord
end

ruby/rails-talkjs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby/rails-talkjs/app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @users = User.all
    gon.users = @users
  end

  def conversation
    @users = User.all
    gon.mainUser = User.find_by(id: 'john.garcia')
    gon.users = @users
  end
end

ruby/rails-talkjs/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/rails-talkjs/app/helpers/chat_helper.rb
module ChatHelper
end

ruby/rails-talkjs/app/views/chat/conversation.html.erb
<%= javascript_import_module_tag "conversation" %>
<div id="user-data" data-users="<%= @users.to_json %>"></div>
<div class = "main-container">
<%= content_tag :button, type: 'button', class: 'chat-button', onclick: "window.location='#{chat_path}'" do %>
  <svg
    xmlns="http://www.w3.org/2000/svg&quot;
    width="16"
    height="16"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
  >
    <path d="m15 18-6-6 6-6" fill="none" />
  </svg>
  John's chats
<% end %>
<div id="talkjs-container">
  <i>Loading chat...</i>
</div>
</div>

ruby/rails-talkjs/app/views/chat/index.html.erb
<div class = "button-container">
<h3 class="index-title">John's chats</h3>
<%= button_to 'Chat with Leroy', chat_conversation_path(@users.second.id), method: 'get', class: 'chat-button' %>
<%= button_to 'Chat with Ryan', chat_conversation_path(@users.third.id), method: 'get', class: 'chat-button' %>
</div>

ruby/rails-talkjs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails - TalkJS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= Gon::Base.render_data %>
    <script>
      (function(t,a,l,k,j,s){
      s=a.createElement('script');s.async=1;s.src='https://cdn.talkjs.com/talk.js';a.head.appendChild(s)
      ;k=t.Promise;t.Talk={v:3,ready:{then:function(f){if(k)return new k(function(r,e){l.push([f,r,e])});l
      .push([f])},catch:function(){return k&&new k()},c:l}};})(window,document,[]);
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>